version: '3.8'

services:
  mongodb:
    image: mongo:5.0
    container_name: ocean_hazard_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: ocean_hazards
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - ocean_hazard_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ocean_hazard_backend
    restart: unless-stopped
    ports:
      - "8001:8001"
    environment:
      - MONGO_URL=mongodb://mongodb:27017
      - EMERGENT_LLM_KEY=${EMERGENT_LLM_KEY}
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
    networks:
      - ocean_hazard_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ocean_hazard_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8001
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - ocean_hazard_network

volumes:
  mongodb_data:

networks:
  ocean_hazard_network:
    driver: bridge